### ISSUE TITLE
[BUILD] .plist -> .xcconfig 기반으로 변경

### ISSUE THREAD

**Issue by jeong-hyeonHwang** [OFFTORIVER/BJGG#195]
**Issue : Feature**
**기존의 `Private.plist`를 통한 Private Key를 관리를 `Private.xcconfig`를 통한 관리로 변경합니다.**

**Description**
1. `.gitignore`에 .xcconfig 추가
2. `Private.plist` 관련 구문 `Private.xcconfig`로 변경
3. plist 관련 에러 xcconfig 에러 추가

**TODO**
- [x] `.gitignore`에 .xcconfig 추가
- [x] `Private.plist` 관련 구문 `Private.xcconfig`로 변경
- [x] plist 관련 에러 xcconfig 에러 추가
