### ISSUE TITLE
[Feat] BbajiHomeViewController 기본 Constraints 작성

### ISSUE THREAD

**Issue by JaewoongLee-swift** [OFFTORIVER/BJGG#23]
**Issue : Feature**
BbajiHomeViewController 기본 Constraints 작성

**Description**
- Figma 디자인을 기반으로 BbajiHomeViewController의 기본 Constraints를 작성해야합니다

**기본 화면 구성은 아래와 같이 분할됩니다.**
[![](https://mermaid.ink/img/pako:eNp10MsOgjAQBdBfIbOWH2BhooDRhJWvjXVR6SA1fZg6xBjg3y1CfCTYVdN77iTTGnIrECI4O34tg2zNTODP7DA_8YtcWo17iffYGnJWKXTHIQ_CMJwGzW7VxU3c860k9fLjKulVJm_0hZIBxd38nKQ1L5x-8G8y1NLRWoxKNYt_1S49wgQ0Os2l8FvX3TAGVKJGBpG_Cix4pYgBM62nvCK7eZgcInIVTqC6Ck6YSO7_S0NUcHV7v6ZCknW9bJ_8TnYA)](https://mermaid.live/edit#pako:eNp10MsOgjAQBdBfIbOWH2BhooDRhJWvjXVR6SA1fZg6xBjg3y1CfCTYVdN77iTTGnIrECI4O34tg2zNTODP7DA_8YtcWo17iffYGnJWKXTHIQ_CMJwGzW7VxU3c860k9fLjKulVJm_0hZIBxd38nKQ1L5x-8G8y1NLRWoxKNYt_1S49wgQ0Os2l8FvX3TAGVKJGBpG_Cix4pYgBM62nvCK7eZgcInIVTqC6Ck6YSO7_S0NUcHV7v6ZCknW9bJ_8TnYA)

**Reference(Optional)**
- 기기별 다른 constraints는 view.safeAreaLayoutGuide를 통해 조절할 예정입니다.

### ⚠️ATTENTION⚠️
- 해당 이슈에선 iPhone13 레이아웃을 대상으로 Constraints를 테스트할 예정입니다. 타 기기는 차후에 Issue 등록 이후 구현할 예정입니다.

### TODO
- [x] ViewController 영역 분할
- [x] BbajiTitleView Constraints 작성
- [x] BbajiListView Constraints 작성
- [x] BbajiListView 내의 BbajiListCollectionView 구현 (BbajiListCollectionViewCell 포함)
