### ISSUE TITLE
[Feat] 빠지 카메라 View Controller 기본 Constraints 작성

### ISSUE THREAD

**Issue by jeong-hyeonHwang** [OFFTORIVER/BJGG#5]
**Issue : Feature**
빠지 카메라 View Controller 기본  Constraints 작성

**Description**
- Figma 디자인을 기반으로 화면의 기본 Constraints를 작성합니다.

**기본 화면 구성은 아래와 같이 분할됩니다.**
[![](https://mermaid.ink/img/pako:eNp10s1q4zAQAOBXGQTtqWVPveRQaGynUZpAaXB3QS5mao9jNbJkZLmhJHn3lZXNOhTqkzzzaUZ_e1aYktiEbSy2NSxfMg3-exDTd_yQ69a4V0m7yGhnjVJk3-D29h4OKR_Ch6lYyk-KsCGLQ-Dt32yPLlQkhjpcV-ZnEwfzm9DVZL_RqyuYhraRSPmv9A88W-OM-2ppBFEA8Z43raKGtEMnjT7-z8endT8oBTtjt9BaU1DXgexgJ10NKQ_xQyJmUjmyENWoN5SvqPAD2TVjqySUmokVbgnu4OTH9CykH7_VSfkoHoOYi9O5wcz604VrmGKxHdE8IH5GXPtitm-HXcEcdamk3oyaB70463Xdu6F5UlVUuJEtAnsSkb9zeKEKC2culv40pJciz1evz7DyRkFMn6RMC4ku8zxIdsN8jwZl6V_NfohkzF9aQxmb-GGJdpuxTB-969sSHSWl9F3YxNmebhj2zqy_dHH-P5lYon-ADZtUqDo6_gW_EM_p)](https://mermaid.live/edit#pako:eNp10s1q4zAQAOBXGQTtqWVPveRQaGynUZpAaXB3QS5mao9jNbJkZLmhJHn3lZXNOhTqkzzzaUZ_e1aYktiEbSy2NSxfMg3-exDTd_yQ69a4V0m7yGhnjVJk3-D29h4OKR_Ch6lYyk-KsCGLQ-Dt32yPLlQkhjpcV-ZnEwfzm9DVZL_RqyuYhraRSPmv9A88W-OM-2ppBFEA8Z43raKGtEMnjT7-z8endT8oBTtjt9BaU1DXgexgJ10NKQ_xQyJmUjmyENWoN5SvqPAD2TVjqySUmokVbgnu4OTH9CykH7_VSfkoHoOYi9O5wcz604VrmGKxHdE8IH5GXPtitm-HXcEcdamk3oyaB70463Xdu6F5UlVUuJEtAnsSkb9zeKEKC2culv40pJciz1evz7DyRkFMn6RMC4ku8zxIdsN8jwZl6V_NfohkzF9aQxmb-GGJdpuxTB-969sSHSWl9F3YxNmebhj2zqy_dHH-P5lYon-ADZtUqDo6_gW_EM_p)

**Reference(Optional)**
- 기기별 다른 Constraints는 safeArea를 통해 조절합니다
-> == view.safeAreaLayoutGuide을 통해 조절합니다.

### ⚠️ATTENTION⚠️
- 해당 이슈에선 **iPhone14 레이아웃만을 대상으로 Constraints를 테스트**합니다.
- Text의 size와 weight는 고려하나, **font는 고려하지 않습니다**.
- Component의 **Color는 고려하지 않습니다.**

### TODO
- [x] ViewController 세 개의 영역으로 분할하기
- [X] SpotInfoView Contraints 작성
- [X] SpotWeatherInfoView Constraints (상단) 작성
- [x] SpotWeatherInfoView Constraints (하단) 작성
